### ISSUE TITLE
Shader export is a mess

### ISSUE THREAD

**Issue by xanathon** [daz3d/DazToC4D#38]
When exporting static props this latest version of the bridge are one big mess when it comes to exporting shaders. Even the quite flawed very first version was way better than this.

Only a diffuse texture is brought over, reflection, normal, bump are all missing. Also in the first version material groups were exported, now you get one material/UV for one object and you loose all metarial information. That leads to manual postwork after importing that is just not doable, because it costs so much time, to rework this into a usable asset.

I will go back to the first version. That had it's problems and did generate the nodes wrong in multiple places, also it had problems in Redshift with specular materials or normal maps plugged into bump nodes, but all in all the first verison needed WAY less postwork than this new version. It is not improved, it is lacking in a lot of places, especially materials and shaders. For me the new version is mostly unusable.

**Comment by brucek5** [comment]
Hi axnathon,
As a user of the Cinema Bridge, I too noticed material creation issues not only with props but also with characters with different types of geoshells. 

This last Bridge update was pretty major with a lot a great features, but must have impacted the material conversion. I'm sure they'll figure it out.

Below is what I captured in my Python log while trying to convert materials to Redshift (I replaced the R21_XXXXXX for this posting):

Traceback (most recent call last):
  File "C:\Users\brucek5\AppData\Roaming\Maxon\Maxon Cinema 4D R21_XXXXXX\plugins\DazToC4D\lib\DtC4DGuiImportDaz.py", line 396, in Command
    rs_mat.execute()
  File "C:\Users\brucek5\AppData\Roaming\Maxon\Maxon Cinema 4D R21_XXXXXX\plugins\DazToC4D\lib\RedshfitMaterials.py", line 71, in execute
    self.make_rsmat(mat, prop)
  File "C:\Users\brucek5\AppData\Roaming\Maxon\Maxon Cinema 4D R21_XXXXXX\plugins\DazToC4D\lib\RedshfitMaterials.py", line 320, in make_rsmat
    self.set_up_diffuse(prop, rs_material, rs)
  File "C:\Users\brucek5\AppData\Roaming\Maxon\Maxon Cinema 4D R21_XXXXXX\plugins\DazToC4D\lib\RedshfitMaterials.py", line 139, in set_up_diffuse
    self.set_gamma(texture_node, "sRGB")
  File "C:\Users\brucek5\AppData\Roaming\Maxon\Maxon Cinema 4D R21_XXXXXX\plugins\DazToC4D\lib\RedshfitMaterials.py", line 93, in set_gamma
    texture[c4d.REDSHIFT_SHADER_TEXTURESAMPLER_TEX0_GAMMAOVERRIDE] = True
AttributeError: 'module' object has no attribute 'REDSHIFT_SHADER_TEXTURESAMPLER_TEX0_GAMMAOVERRIDE'

**Comment by xanathon** [comment]
That is not a problem in the latest version, it already was there from the first release of this third developer team trying their hands on this.

The missing texture mapping is not only a Redshift problem, it also does not work with standard C4D materials.

I have no idea how something like this can even be release in this buggy state.
