### ISSUE TITLE
Python Script error in Cinema 4D plugin.

### ISSUE THREAD

**Issue by nuxil** [daz3d/DazToC4D#60]
Hello.

I am running C4D R18, 
Importing models causes script errors when i try to "import" a model though the button "Daz to C4D"

I am using the latest release. "2024-alpha-preview-002" and have followed the install instructions found here:
https://github.com/daz3d/DazToC4D/releases/tag/2024-alpha-preview-002

The error you can see in C4d's console is:

```
Traceback (most recent call last):
  File "H:\Programs\C4d-R18\plugins\DazToC4D\lib\DtC4DGuiImportDaz.py", line 314, in Command
    CustomImports().auto_import_genesis(sss_value, normal_value, bump_value)
  File "H:\Programs\C4d-R18\plugins\DazToC4D\lib\CustomImports.py", line 50, in auto_import_genesis
    fbx_path = dtu.get_fbx_path()
  File "H:\Programs\C4d-R18\plugins\DazToC4D\lib\DtuLoader.py", line 66, in get_fbx_path
    self.load_fbx_path()
  File "H:\Programs\C4d-R18\plugins\DazToC4D\lib\DtuLoader.py", line 61, in load_fbx_path
    dtu_dict = self.get_dtu_dict()
  File "H:\Programs\C4d-R18\plugins\DazToC4D\lib\DtuLoader.py", line 35, in get_dtu_dict
    self.load_dtu()
  File "H:\Programs\C4d-R18\plugins\DazToC4D\lib\DtuLoader.py", line 30, in load_dtu
    with open(dtu, "r", encoding="utf-8") as data:
TypeError: 'encoding' is an invalid keyword argument for this function
```

**Comment by nuxil** [comment]
I am messing around a bit with Daz again.
I discovered by accident that this error seams to be related to morphs.
What caused this error? not 100% sure tho.!

But in the "Daz exporter settings" i had checked the export Morphs.
And I had selected **All the Morphs**, so the error will occure in Cinema 4d when importing when i had this set.

I have not gone though the list off all morphs to find out which one it is thats causing the error.
But when i removed all the morphs from the Exporter setting and only added the few facial morphs i needed.
No errors was showing in Cinema 4D, and every thing is good.

Btw. this error is also in Cinema 2023
